# Site settings
title: Crowsmos
email: gondorle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.braincrow.com" # the base hostname & protocol for your site
twitter_username: gondorle
github_username:  gondorle
css: "blue"
scroll-cursor: "#131313"
scroll-rail: "#131313"

# Build settings
markdown: kramdown
highlighter: pygments
lsi: false
safe: false
